M48
; DRILL file {KiCad (6.0.10-0)} date Friday, January 20, 2023 at 09:59:05 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-20T21:59:05-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X0.8661Y-2.15
X0.8661Y-2.55
X1.1417Y-2.15
X1.1417Y-2.55
T0
M30
